apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-api
spec:
  replicas: 2

  selector:
    matchLabels:
      app: spam-api

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  template:
    metadata:
      labels:
        app: spam-api

    spec:
      containers:
        - name: api
          image: spam-api-q4:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 3
